In [3]:
#Write python program to demonstrate Perceptron NN to recognize even and odd numbers. Given numbers are in ASCII from 0 to 1

In [4]:
import numpy as np

# Define the perceptron class
class Perceptron:
	def __init__(self, input_size=7, lr=0.1):
		self.W = np.zeros(input_size + 1)
		self.lr = lr

	def activation_fn(self, x):
		return 1 if x >= 0 else 0

	def predict(self, x):
		x = np.insert(x, 0, 1)
		z = self.W.T.dot(x)
		a = self.activation_fn(z)
		return a

	def train(self, X, Y, epochs):
		for _ in range(epochs):
			for i in range(Y.shape[0]):
				x = X[i]
				y = self.predict(x)
				e = Y[i] - y
				self.W = self.W + self.lr * e * np.insert(x, 0, 1)

# Define the input data and labels
X = np.array([
[0,0,0,0,0,0,0], # 0
[0,0,0,0,0,0,1], # 1
[0,0,0,0,0,1,0], # 2
[0,0,0,0,0,1,1], # 3
[0,0,0,0,1,0,0], # 4
[0,0,0,0,1,0,1], # 5
[0,0,0,0,1,1,0], # 6
[0,0,0,0,1,1,1], # 7
[0,0,0,1,0,0,0], # 8
[0,0,0,1,0,0,1], # 9

])

Y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

# Create the perceptron and train it
perceptron = Perceptron()
perceptron.train(X, Y, epochs=100)

# Test the perceptron on some input data
test_X = np.array([
[0,0,0,0,0,0,0], # 0
[0,0,0,0,0,0,1], # 1
[0,0,0,0,0,1,0], # 2
[0,0,0,0,0,1,1], # 3
[0,0,0,0,1,0,0], # 4
[0,0,0,0,1,0,1], # 5
[0,0,0,0,1,1,0], # 6
[0,0,0,0,1,1,1], # 7
[0,0,0,1,0,0,0], # 8
[0,0,0,1,0,0,1], # 9
])

for i in range(test_X.shape[0]):
	x = test_X[i]
	y = perceptron.predict(x)
	print(f'{x} is {"even" if y == 0 else "odd"}')

[0 0 0 0 0 0 0] is even
[0 0 0 0 0 0 1] is odd
[0 0 0 0 0 1 0] is even
[0 0 0 0 0 1 1] is odd
[0 0 0 0 1 0 0] is even
[0 0 0 0 1 0 1] is odd
[0 0 0 0 1 1 0] is even
[0 0 0 0 1 1 1] is odd
[0 0 0 1 0 0 0] is even
[0 0 0 1 0 0 1] is odd


In [5]:
'''
Perceptron Class:
__init__: Initializes the perceptron with zero weights and a learning rate.
activation_fn: Defines the activation function. Here, it's a step function, returning 1 if the input is greater than or equal to zero, otherwise 0.
predict: Predicts the output based on the input and current weights. It inserts a bias term (1) to the input vector, computes the dot product with weights, and applies the activation function.
train: Performs training on the perceptron. It iterates over the dataset for a specified number of epochs, updating weights based on prediction errors.
Input Data and Labels (X and Y):
X: Input data containing binary vectors representing numbers from 0 to 9.
Y: Corresponding labels indicating whether the number is even (0) or odd (1).
Training:
An instance of Perceptron is created.
train method is called to train the perceptron on the input data X and labels Y for a specified number of epochs (100 in this case).
Testing:
The trained perceptron is tested on a separate set of input data test_X.
For each input vector in test_X, the perceptron predicts whether the number is even or odd and prints the result.

'''

"\nPerceptron Class:\n__init__: Initializes the perceptron with zero weights and a learning rate.\nactivation_fn: Defines the activation function. Here, it's a step function, returning 1 if the input is greater than or equal to zero, otherwise 0.\npredict: Predicts the output based on the input and current weights. It inserts a bias term (1) to the input vector, computes the dot product with weights, and applies the activation function.\ntrain: Performs training on the perceptron. It iterates over the dataset for a specified number of epochs, updating weights based on prediction errors.\nInput Data and Labels (X and Y):\nX: Input data containing binary vectors representing numbers from 0 to 9.\nY: Corresponding labels indicating whether the number is even (0) or odd (1).\nTraining:\nAn instance of Perceptron is created.\ntrain method is called to train the perceptron on the input data X and labels Y for a specified number of epochs (100 in this case).\nTesting:\nThe trained perceptron 